name: Create Release Zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Set VERSION variable
      run: sed -i "s/VERSION = .*/VERSION = ${{ github.ref }}/" Honeycomb-Bravo-Plugin/globals.lua

    - name: Zip the code
      run: zip -r release-${{ github.ref }}.zip .

    - name: Upload Release
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release-${{ github.ref }}.zip